DROP TABLE IF EXISTS cms;
;
INSERT INTO cms VALUES('212','','','EEEE','209');
INSERT INTO cms VALUES('211','','DDDD','','208');
INSERT INTO cms VALUES('210','','','CCCC','209');
INSERT INTO cms VALUES('209','','BBBB','','208');
INSERT INTO cms VALUES('208','AAAA','','','');
